package com.lxsc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling
@EnableEurekaClient
@EnableFeignClients
public class LxscTimerApplication {

    public static void main(String[] args) {
        SpringApplication.run(LxscTimerApplication.class, args);
    }

}
